version: 2.1
orbs:
  terraform-config-validator: circleci/terraform-config-validator@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  python: circleci/python@2.1

filters: &filters
  tags:
    only: /.*/

jobs:
  test-terraform-config-validator-with-is-test-mode:
    executor: python/default
    steps:
      - checkout
      - terraform-config-validator/validate:
          is-test-mode: true
          tf-plan-json-path: src/scripts/fixtures/sample-digraph-tf-plan-output.json
  persist-workspace-with-plan-output:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run:
          command: mkdir -p /tmp/dir
      - run:
          command: cp src/scripts/fixtures/sample-digraph-tf-plan-output.json /tmp/dir/sample-digraph-tf-plan-output.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - dir

workflows:
  test-deploy:
    jobs:
      - test-terraform-config-validator-with-is-test-mode:
          filters: *filters
      - persist-workspace-with-plan-output:
          filters: *filters
      # - terraform-config-validator/validate:
      #     filters: *filters
      #     checkout: true
      #     attach-workspace: true
      #     workspace-path: /tmp
      #     tf-plan-json-path: /tmp/dir/sample-digraph-tf-plan-output.json
      #     requires:
      #       - persist-workspace-with-plan-output
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: di-graph/terraform-config-validator
          vcs-type: << pipeline.project.type >>
          pub-type: dev
          requires:
            - orb-tools/pack
            - persist-workspace-with-plan-output
            - test-terraform-config-validator-with-is-test-mode
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
